#debug: true
bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  creator-id: ${BOT_CREATOR}

app-config:
  rabbit:
    tgActionRoutingKey: tgAction
    tgActionQueueName:  container.hostname.queue
    tgActionExchangeName: tgAction.exchange

spring:
  application:
    name: FastSearchCommandProcessor
  data:
    mongodb:
      host: mongo01
      port: 27017
      database: testDB
#      authentication-database: admin
#      username: testUser
#      password: testPassword
      replica-set-name: rs0
      ssl:
        enabled: true
        bundle: mongo-client

  #      auto-index-creation: true
  #  server: port=8081

  elasticsearch:
#    uris: https://192.168.100.11:9200
    uris: https://elastic01:9200
    username: elastic
    password: testPassword
    connection-timeout: 10000s
    socket-timeout: 10000s
    #    socket-keep-alive:
    #    path-prefix:
    restclient:
      #      sniffer:
      ssl:
        bundle: elastic-client
    #удалил для удаленного      ssl:
    #удалил для удаленного        bundle: elastic-client

    #---SslAutoConfiguration--------------------------
  ssl:
    bundle:
      #      jks.*:
      pem:
        elastic-client:
          truststore:
            certificate: "classpath:ca/ca.pem"
          keystore:
            certificate: "classpath:elastic/cert/telegramAppElastic.pem"
            private-key: "classpath:elastic/cert/telegramAppElastic.key"
        rabbit-client:
          keystore:
            certificate: "classpath:rabbit/telegramAppRabbit.pem"
            private-key: "classpath:rabbit/telegramAppRabbit.key"
          #            private-key-password:
          truststore:
            certificate: "classpath:ca/ca.pem"
  #      watch:
  #        file:
  #          quiet-period:
        mongo-client:
          truststore:
            certificate: "classpath:ca/ca.pem"
          #      watch:
          #        file:
          #          quiet-period:
          keystore:
            certificate: "classpath:mongo/telegramAppMongo.pem"
            private-key: "classpath:mongo/telegramAppMongo.key"

  #--TaskExecutionAutoConfiguration------------------------
  task:
    execution:
      threadNamePrefix: Fastsearch-Command-Processor-Thread-
      pool:
        core-size: 4
        max-size: 10
        allow-core-thread-timeout: true
        keep-alive: PT30S
        queue-capacity: 200
      shutdown:
        await-termination: true
        await-termination-period: PT30S  #60 sec example - P3DT5H40M30S = 3Days, 5Hours, 40 Minutes and 30 Seconds

    #-----TaskSchedulingAutoConfiguration-----------------------
  scheduling:
    threadNamePrefix: Bot-Scheduling-caching-Thread-
    pool:
      size: 1
    shutdown:
      await-termination: true
      await-termination-period: PT10S
  # -----------------------------------------------------

  #--------------------------------------------------------------------------
  #MessageSourceAutoConfiguration------------
  messages:
    basename: i8n/messages
    use-code-as-default-message: true
    fallback-to-system-locale: false
    encoding: UTF-8
    always-use-message-format: false
    cache-duration: -1
  #-------------------------------------------

  rabbitmq:
    addresses: rabbit01:5671
#    address-shuffle-mode: inorder
#    host: localhost
#    port: 5672
    username: telegramApp
#    password: guest
#    virtual-host:
#    cache:
#      channel:
#        size:
#        checkout-timeout:
#      connection:
#        mode: connection

#        size: установить в кол-во нод
#    publisher-confirm-type: none(def)

#    publisher-returns: false(def)
#    connection-timeout: ?
#    requested-heartbeat: ?
#    max-inbound-message-body-size:
#    requested-channel-max:

    listener:
      type: direct
      direct:
#        acknowledge-mode: auto
#        auto-startup: true
#        default-requeue-rejected: true
#        missing-queues-fatal: true
        prefetch: 2
        consumers-per-queue: 2
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
#          max-interval: 10000ms
          multiplier: 2
          stateless: true
    ssl:
      enabled: true
      bundle: rabbit-client
      algorithm: TLSv1.3

#  logging:
#    level:
#      tracer: TRACE
#      org:
#        springframework:
#          jdbc:
#            core:
#              #          core: TRACE
#              StatementCreatorUtils: TRACE
#              JdbcTemplate: TRACE
#
#          data:
#            elasticsearch:
#              client:
#                WIRE: TRACE
logging:
  level:
    tracer: TRACE
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
#          elasticsearch:
#            client:
#              WIRE: TRACE