debug: true
bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  creator-id: ${BOT_CREATOR}
app:
  rabbit:
    tgActionExchangeName: tgAction.exchange
  auth-path: ${AUTH_PATH}

spring:
  application:
    name: multisearch-processor
  main.banner-mode: off
  data:
    mongodb:
      host: mongo01
      port: 27017
      database: testDB
#      auto-index-creation: true
#      authentication-database: admin
#      username: testUser
#      password: testPassword
      replica-set-name: rs0
      ssl:
        enabled: true
        bundle: mongo-client

  #      auto-index-creation: true
  #  server: port=8081

  elasticsearch:
#    uris: https://192.168.100.11:9200
    uris: https://elastic01:9200
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 10000s
    socket-timeout: 10000s
    #    socket-keep-alive:
    #    path-prefix:
    restclient:
      #      sniffer:
      ssl:
        bundle: elastic-client
    #удалил для удаленного      ssl:
    #удалил для удаленного        bundle: elastic-client

    #---SslAutoConfiguration--------------------------
  ssl:
    bundle:
      #      jks.*:
      pem:
        elastic-client:
          truststore:
            certificate: "file:${app.auth-path}/ca.pem"
        rabbit-client:
          keystore:
            certificate: "file:${app.auth-path}/tgAppRabbit.pem"
            private-key: "file:${app.auth-path}/tgAppRabbit.key"
          #            private-key-password:
          truststore:
            certificate: "file:${app.auth-path}/ca.pem"
  #      watch:
  #        file:
  #          quiet-period:
        mongo-client:
          truststore:
            certificate: "file:${app.auth-path}/ca.pem"
          #      watch:
          #        file:
          #          quiet-period:
          keystore:
            certificate: "file:${app.auth-path}/tgAppMongo.pem"
            private-key: "file:${app.auth-path}/tgAppMongo.key"

  #--TaskExecutionAutoConfiguration------------------------
  task:
    execution:
      threadNamePrefix: Fastsearch-Command-Processor-Thread-
      pool:
        core-size: 4
        max-size: 10
        allow-core-thread-timeout: true
        keep-alive: PT30S
        queue-capacity: 200
      shutdown:
        await-termination: true
        await-termination-period: PT30S  #60 sec example - P3DT5H40M30S = 3Days, 5Hours, 40 Minutes and 30 Seconds

    #-----TaskSchedulingAutoConfiguration-----------------------
    scheduling:
      threadNamePrefix: Bot-Scheduling-caching-Thread-
      pool:
        size: 1
      shutdown:
        await-termination: true
        await-termination-period: PT10S
  # -----------------------------------------------------

  #--------------------------------------------------------------------------
  #MessageSourceAutoConfiguration------------
  messages:
    basename: i8n/messages
    use-code-as-default-message: true
    fallback-to-system-locale: false
    encoding: UTF-8
    always-use-message-format: false
    cache-duration: -1
  #-------------------------------------------
  #--------------------------------------------------------------------------
  rabbitmq:
    addresses: rabbit01:5671
#    address-shuffle-mode: inorder
#    host: localhost
#    port: 5672
    username: telegramApp
#    password: guest
#    virtual-host:
#    cache:
#      channel:
#        size:
#        checkout-timeout:
#      connection:
#        mode: connection
#        size: установить в кол-во нод
#    publisher-confirm-type: none(def)
#    publisher-returns: false(def)
#    connection-timeout: ?
#    requested-heartbeat: ?
#    max-inbound-message-body-size:
#    requested-channel-max:
    listener:
      type: direct
      direct:
#        acknowledge-mode: auto
#        auto-startup: true
        default-requeue-rejected: false
#        missing-queues-fatal: true
        prefetch: 3
        consumers-per-queue: 3
#        retry:
#          enabled: true
#          initial-interval: 400ms
#          max-attempts: 3
#          max-interval: 10000ms
#          multiplier: 2
#          stateless: true
    ssl:
      enabled: true
      bundle: rabbit-client
      algorithm: TLSv1.3
  #-------------------------------------------

#  logging:
#    level:
#      tracer: TRACE
#      org:
#        springframework:
#          jdbc:
#            core:
#              #          core: TRACE
#              StatementCreatorUtils: TRACE
#              JdbcTemplate: TRACE
#
#          data:
#            elasticsearch:
#              client:
#                WIRE: TRACE

logging:
  structured:
    format:
      console: ecs
  level:
    tracer: TRACE
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
#          elasticsearch:
#            client:
#              WIRE: TRACE
#management:
#  endpoints:
#    web:
#      exposure:
#        include: [health, prometheus]
#  endpoint:
#    prometheus:
#      enabled: true
#  server:
#    port: 8080

management:
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${HOSTNAME}
  elastic:
    metrics:
      export:
        enabled: true
        host: https://elastic01:9200
        step: 10s
        user-name: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        index: metrics-multisearch
